knpu_oauth2_client:
    clients:
        spotify:
            # must be "spotify" - it activates that type!
            type: spotify
            # add and set these environment variables in your .env files
            client_id: '%env(SPOTIFY_ID)%'
            client_secret: '%env(SPOTIFY_SECRET)%'
            # a route name you'll create
            redirect_route: connect_spotify_check
            redirect_params: {}
